---
- name: copy file from server1 to server2
  hosts: 172.31.34.71
  tasks:
    - name: Fetch file from server1
      fetch:
        src: file1
        dest: /tmp
- name: paste file to server2
  hosts: 172.31.35.77
  tasks:
    - name: paste to server2 
      copy:
        src: /tmp/172.31.34.71/file1
        dest: /tmp
...            
