---
- name: Implement handlers
  hosts: all
  tasks:
    - name: implement apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: edit index.html file
      copy:
        content: "I Love You"
        dest: /var/www/html/index.html
      notify: Restart apache
  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted    
    - name: check url response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.34.71
        - http://172.31.35.77
...          
